### ISSUE TITLE
Feasibility of computation of IW-SSIM on CUDA

### ISSUE THREAD

**Issue by snk4tr** [photosynthesis-team/piq#310]
**Describe the bug**
Computation of IW-SSIM on CPU works fine. However, an attempt to compute this metric on CUDA causes `An illegal memory access error`.

**To Reproduce**
1. Checkout to [feature/extend_bench](https://github.com/photosynthesis-team/piq/tree/feature/extend_bench)
2. Run `tests/results_benchmark.py` with `--metrics IW-SSIM`
3. See error

**Expected behavior**
Metric can is computed both on CPU and GPU.

**Screenshots**
![telegram-cloud-photo-size-2-5330155183314942109-y](https://user-images.githubusercontent.com/24959314/160283092-24d404aa-9f25-4ede-952e-ddb12bd91cef.jpg)

**Additional context**
The IW-SSIM code has not been tested on GPU

**Comment by denproc** [comment]
Hi @snk4tr, thank you for bug report!

The reason for such error is in line [370](https://github.com/photosynthesis-team/piq/blob/9da71aab85e1f9452ffe6b5bb0b215e76aad7555/piq/iw_ssim.py#L370). The tensor is created on `cpu`. 
The bug will be fixed soon.

**Comment by denproc** [comment]
I managed to fix it for `torch >=1.5.1, <1.8.0 | >=1.10.0`.
Unfortunately, there are bugs in `torch == 1.8.0,1.8.1,1.9.0,1.9.1` that produce the error/warning shown in the screenshots. 

When using `torch.simeig`:
1.8.0; 1.8.1 ERROR:
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/22414094/160702492-3b8c06f8-1915-4ca5-b6aa-a95e4db988e2.png">
1.9.0; 1.9.1 WARNING:
![image](https://user-images.githubusercontent.com/22414094/160711898-479b317c-9592-4ce4-af47-ce3642644684.png)


When using `torch.linalg.eigh`:
1.9.0, 1.9.1 ERROR:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/22414094/160702532-ab43b1d1-e9c4-4bf3-8815-e58165660858.png">

Therefore, we should choose a solution for mention versions.
I would suggest to
- make user update(or downgrade) `torch!=1.8`
- use `symeig` for `torch==1.9` with warning that `torch.symeig` will be deprecated in favour of `torch.linalg.eigh`.

cc'd @snk4tr @zakajd

**Comment by snk4tr** [comment]
@denproc thanks for investigating this!
I is really unfortunate that new versions of PyTorch have such bugs in pretty widely used functions. Are these bugs at least reported?
I like the proposed approach. Please proceed with PR.

**Comment by denproc** [comment]
@snk4tr 
The issue was fixed in `torch>=1.10` but I don't have the link to the issue/PR in PyTorch repo.
